name       : gfbgraph
version    : 0.2.5
release    : 13
source     :
    - https://gitlab.gnome.org/GNOME/libgfbgraph/-/archive/v_0_2_5/libgfbgraph-v_0_2_5.tar.gz : 3f53e548464dd64b0887b9f2d7093bd3367e1e4f6932a7c79f527b66255c0804
homepage   : https://gitlab.gnome.org/GNOME/libgfbgraph
license    : LGPL-2.1-or-later
component  : desktop.gnome.core
summary    : GFBGraph is a GLib/GObject wrapper for the Facebook API
description: |
    GFBGraph is a GLib/GObject wrapper for the Facebook API.
builddeps  :
    - pkgconfig(goa-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
setup      : |
    %patch -p1 < $pkgfiles/0001-Strip-out-docs.patch
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
