name       : gfbgraph
version    : 0.2.4
release    : 10
source     :
    - https://download.gnome.org/sources/gfbgraph/0.2/gfbgraph-0.2.4.tar.xz : 6065391f35e7335588cc6b0cc4c1abbce7341488573a654551264cb9793b9379
license    : LGPL-3.0-only
component  : desktop.gnome.core
summary    : GFBGraph is a GLib/GObject wrapper for the Facebook API.
description: |
    GFBGraph is a GLib/GObject wrapper for the Facebook API.
builddeps  :
    - pkgconfig(goa-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
setup      : |
    %patch -p1 < $pkgfiles/0001-Strip-out-docs.patch
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
